export enum screenNames {
  INITIAL_SCREEN = 'initialScreen',
  USER_PROFILE = 'userProfile',
  RECOVERY_SCREEN = 'recoveryScreen',
  QUIZ_SELECTION = 'quizSelection',
  QUIZ_SCREEN = 'quizScreen',
  RESULT = 'result',
  SIGN_UP = 'signUp',
  SIGN_IN = 'signIn',
  DISCOVER = 'discover',
  HOME = 'home',
  STATISTICS = 'statistics',
  TOPICS = 'topics',
  AUTH_STACK = 'authStack',
  TABS_STACK = 'tabsStack',
  PROFILE = 'PROFILE',
}
